"""empty message

Revision ID: 46c6994a5739
Revises: 6d9513140d15
Create Date: 2022-10-26 21:51:29.844657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c6994a5739'
down_revision = '6d9513140d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('empresa', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'empresa')
    # ### end Alembic commands ###
