"""Primeira migracao

Revision ID: 7aa6d267fffe
Revises: 
Create Date: 2022-10-25 12:31:43.893270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa6d267fffe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razaoSocial', sa.String(length=128), nullable=True),
    sa.Column('cnpj', sa.Integer(), nullable=True),
    sa.Column('nomeFantasia', sa.String(length=128), nullable=True),
    sa.Column('telefone', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('cep', sa.String(length=128), nullable=True),
    sa.Column('logradouro', sa.String(length=128), nullable=True),
    sa.Column('bairro', sa.String(length=128), nullable=True),
    sa.Column('numero', sa.String(length=128), nullable=True),
    sa.Column('cidade', sa.String(length=128), nullable=True),
    sa.Column('estado', sa.String(length=128), nullable=True),
    sa.Column('criado_em', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=128), nullable=True),
    sa.Column('senha', sa.String(length=128), nullable=True),
    sa.Column('cpf', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('logradouro', sa.String(length=128), nullable=True),
    sa.Column('numero', sa.String(length=128), nullable=True),
    sa.Column('complemento', sa.String(length=128), nullable=True),
    sa.Column('bairro', sa.String(length=128), nullable=True),
    sa.Column('cep', sa.String(length=128), nullable=True),
    sa.Column('telefone', sa.String(length=128), nullable=True),
    sa.Column('estado', sa.String(length=128), nullable=True),
    sa.Column('cidade', sa.String(length=128), nullable=True),
    sa.Column('criado_em', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('empresa')
    # ### end Alembic commands ###
