"""empty message

Revision ID: 931d39aa85c1
Revises: 61b6bd288c35
Create Date: 2022-10-25 12:42:12.912365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931d39aa85c1'
down_revision = '61b6bd288c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razaoSocial', sa.String(length=128), nullable=True),
    sa.Column('cnpj', sa.Integer(), nullable=True),
    sa.Column('nomeFantasia', sa.String(length=128), nullable=True),
    sa.Column('telefone', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('cep', sa.String(length=128), nullable=True),
    sa.Column('logradouro', sa.String(length=128), nullable=True),
    sa.Column('bairro', sa.String(length=128), nullable=True),
    sa.Column('numero', sa.String(length=128), nullable=True),
    sa.Column('cidade', sa.String(length=128), nullable=True),
    sa.Column('estado', sa.String(length=128), nullable=True),
    sa.Column('criado_em', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=128), nullable=True),
    sa.Column('senha', sa.String(length=128), nullable=True),
    sa.Column('cpf', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('logradouro', sa.String(length=128), nullable=True),
    sa.Column('numero', sa.String(length=128), nullable=True),
    sa.Column('complemento', sa.String(length=128), nullable=True),
    sa.Column('bairro', sa.String(length=128), nullable=True),
    sa.Column('cep', sa.String(length=128), nullable=True),
    sa.Column('telefone', sa.String(length=128), nullable=True),
    sa.Column('estado', sa.String(length=128), nullable=True),
    sa.Column('cidade', sa.String(length=128), nullable=True),
    sa.Column('criado_em', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('empresa')
    # ### end Alembic commands ###
