"""empty message

Revision ID: ec6e8d189416
Revises: 931d39aa85c1
Create Date: 2022-10-25 20:18:44.152284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec6e8d189416'
down_revision = '931d39aa85c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razaoSocial', sa.String(length=128), nullable=True),
    sa.Column('cnpj', sa.Integer(), nullable=True),
    sa.Column('nomeFantasia', sa.String(length=128), nullable=True),
    sa.Column('telefone', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('cep', sa.String(length=128), nullable=True),
    sa.Column('logradouro', sa.String(length=128), nullable=True),
    sa.Column('bairro', sa.String(length=128), nullable=True),
    sa.Column('numero', sa.String(length=128), nullable=True),
    sa.Column('cidade', sa.String(length=128), nullable=True),
    sa.Column('estado', sa.String(length=128), nullable=True),
    sa.Column('criado_em', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('empresa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('razaoSocial', sa.VARCHAR(length=128), nullable=True),
    sa.Column('cnpj', sa.INTEGER(), nullable=True),
    sa.Column('nomeFantasia', sa.VARCHAR(length=128), nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=128), nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
    sa.Column('cep', sa.VARCHAR(length=128), nullable=True),
    sa.Column('logradouro', sa.VARCHAR(length=128), nullable=True),
    sa.Column('bairro', sa.VARCHAR(length=128), nullable=True),
    sa.Column('numero', sa.VARCHAR(length=128), nullable=True),
    sa.Column('cidade', sa.VARCHAR(length=128), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=128), nullable=True),
    sa.Column('criado_em', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('empresas')
    # ### end Alembic commands ###
